### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by ashirviskas** [Vitzual/NeonSundown#1]
Just wanted to say that I love the game! It is really fun and comparing to the early previews I see a huge progress being made.

I've been playing through steam using the compatibility layer and while it feels and functions great, a native version could possibly be even more amazing. I still haven't tried running this project on my own, but I suppose, it would not be hard to compile a linux version?

Either way, thank you for this game.

**Comment by bonn2** [comment]
Was in the room for this conversation, but Ben has the final say.

The reason that there isn't a native linux version is because Proton is so good. Neither me or Ben have a box we can dedicate to linux testing (and dual booting would take up way to much time), so we would just be compiling it blind. That might be fine most of the time, but we have had a few cases where linux specific bugs have appeared by doing that (one particularly nasty one was a transparency bug in Vectorio). Therefore we just decided to not build a native one, because in our eyes the proton layer will likely be more reliable than untested native builds, see the game `Golf with Friends` for an example of this.

Once again Ben has the final say, but that was the rough logic on why it was decided to not release a native linux build.

**Comment by ashirviskas** [comment]
I understand, it doesn't make sense to spend too many resources if a Proton version works well enough.

Thank you for the answer.
